# 端口号
server:
  port: 11111

spring:
  # MySQL数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/shop_user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  # Redis数据库配置
  redis:
    host: 192.168.1.100
    password: 123456
    port: 6379

mybatis-plus:
  configuration:
    # MyBatis-Plus打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


