spring:
  profiles:
    active: dev
  application:
    name: shop-user-service
  # 邮箱服务配置
  mail:
    host: smtp.qq.com
    username: tianzhang.chn@qq.com
    password: olsstrqeuhwbdedj
#    启动ssl安全连接就打开注释
#    port: 465
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true

mybatis-plus:
  global-config:
    db-config:
      # 主键策略
      id-type: assign_id

qcloud:
  # 腾讯云子账号密钥
  secret-id: AKIDSoBNNBnBKH28zd4ILBpFSRDnALI2cz73
  secret-key: nNiqlSvEJCrHTTFm8IEvOccOuCi17zyz
  # 存储桶
  cos:
    region-name: ap-shanghai
    bucket-name: shop-1314926265

