spring:
  profiles:
    active: dev
  application:
    name: shop-user-service
  # 邮箱服务配置
  mail:
    host: smtp.qq.com
    username: tianzhang.chn@qq.com
    password: olsstrqeuhwbdedj
#    启动ssl安全连接就打开注释
#    port: 465
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true

mybatis-plus:
  global-config:
    db-config:
      # 主键策略
      id-type: assign_id
