spring:
  profiles:
    active: dev
  application:
    name: shop-user-service

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

shop:
  jackson:
    local-date-time-format: yyyy-MM-dd HH:mm:ss